boot: zephyr: Kconfig
unisoc/mcuboot pull request #2
Opened 2019-03-05 03:38 UTC by chinli

- modify the BOOT_MAX_IMG_SECTORS to 256

Signed-off-by: frank.lee <frank.lee@unisoc.com>

2019-03-08 08:32 UTC, kelvincheung approved these changes

2019-03-08 08:52 UTC, easonxiang requested changes
Can you please set CONFIG_BOOT_MAX_IMG_SECTORS in prj.conf instead of modify Kconfig.

2019-03-08 09:07 UTC, chinli commented
> 
> 
> Can you please set CONFIG_BOOT_MAX_IMG_SECTORS in prj.conf instead of modify Kconfig.

In my opinion, prj.conf used to config app compile option, but CONFIG_BOOT_MAX_IMG_SECTORS was  just belong to MCUBOOT, if we setted in prj.conf, user maybe confused.

2019-03-09 00:11 UTC, easonxiang approved these changes

2019-03-09 07:38 UTC, merged